/* Generated by Together */

#include "Stdafx.h"
#include "CCellData.h"
#include "../Util/Common.h" //191227 JSH
#include "../Util/MinUtilExt.h"
#include "../Util/MyProgressWnd.h"

CCellData::CCellData(CString strFileName, CString strPath) : CFileManager(strFileName, strPath)
{
	memset(m_dXu_Tab_Pitch, 0, sizeof(m_dXu_Tab_Pitch));
    memset(m_dXd_Tab_Pitch, 0, sizeof(m_dXd_Tab_Pitch));
    memset(m_dY_Tab_Pitch, 0, sizeof(m_dY_Tab_Pitch));

	/** Model Data */
    m_dCellSize_X = 0.0;
    m_dCellSize_Y = 0.0;
    m_flgUse_Xu = 0;
    m_dXu_CellMark_Pos_X = 0.0;
    m_dXu_CellMark_Pos_Y = 0.0;
    m_dXu_CellMark_Distance = 0.0;
    m_flgUse_Xd = 0;
    m_dXd_CellMark_Pos_X = 0.0;
    m_dXd_CellMark_Pos_Y = 0.0;
    m_dXd_CellMark_Distance = 0.0;
    m_flgUse_Y = 0;
    m_dY_CellMark_Pos_X = 0.0;
    m_dY_CellMark_Pos_Y = 0.0;
    m_dY_CellMark_Distance = 0.0;
    m_flgUse_YR = 0;
    m_dYR_CellMark_Pos_X = 0.0;
    m_dYR_CellMark_Pos_Y = 0.0;
    m_dYR_CellMark_Distance = 0.0;
    m_nCell_Input_Direction = 0;
    m_nCell_Output_Direction = 0;
    /**Tab 관련 Data [48개]*/
    m_dXu_Tab_Qty = 0.0;
    m_dXd_Tab_Qty = 0.0;
    m_dY_Tab_Qty = 0.0;
    /** Tab 관련 Data [22개] */
    m_dR_Lead_Pitch_X = 0.0;
    m_dR_Lead_Pitch_Y = 0.0;
    m_dC_Lead_Pitch_X = 0.0;
    m_dC_Lead_Pitch_Y = 0.0;
    m_dLead_Width_Value_X = 0.0;
    m_dLead_Width_Value_Y = 0.0;
    m_dTape_Pitch_Value_X = 0.0;
    m_dTape_Pitch_Value_Y = 0.0;
    m_dSprocket_Value_X = 0.0;
    m_dSprocket_Value_Y = 0.0;
    m_nTab_Direction_X = 0;
    m_nTab_Direction_Y = 0;
    m_dTheta_Tolerance_X = 0.0;
    m_dTheta_Tolerance_Y = 0.0;
    m_dX_Tab_Center_X = 0.0;
    m_dX_Tab_Center_Y = 0.0;
    m_dY_Tab_Center_X = 0.0;
    m_dY_Tab_Center_Y = 0.0;
    m_nBad_Tab_Count_X = 0;
    m_nBad_Tab_Count_Y = 0;
    m_nVisionSceneNumber = 0;
    m_dCellThickness = 0.0;
    m_dPolThickness = 0.0;
	m_dYSideSelect = 0.0;
	m_nUsingStageSelect = 0;
	m_dMarkToStageedgeLengthX = 0;
	m_dMarkToStageedgeLengthY = 0;
}

CCellData::CCellData(CString strFileName) : CFileManager(strFileName)
{
	memset(m_dXu_Tab_Pitch, 0, sizeof(m_dXu_Tab_Pitch));
    memset(m_dXd_Tab_Pitch, 0, sizeof(m_dXd_Tab_Pitch));
    memset(m_dY_Tab_Pitch, 0, sizeof(m_dY_Tab_Pitch));

	/** Model Data */
    m_dCellSize_X = 0.0;
    m_dCellSize_Y = 0.0;
    m_flgUse_Xu = 0;
    m_dXu_CellMark_Pos_X = 0.0;
    m_dXu_CellMark_Pos_Y = 0.0;
    m_dXu_CellMark_Distance = 0.0;
    m_flgUse_Xd = 0;
    m_dXd_CellMark_Pos_X = 0.0;
    m_dXd_CellMark_Pos_Y = 0.0;
    m_dXd_CellMark_Distance = 0.0;
    m_flgUse_Y = 0;
    m_dY_CellMark_Pos_X = 0.0;
    m_dY_CellMark_Pos_Y = 0.0;
    m_dY_CellMark_Distance = 0.0;
    m_flgUse_YR = 0;
    m_dYR_CellMark_Pos_X = 0.0;
    m_dYR_CellMark_Pos_Y = 0.0;
    m_dYR_CellMark_Distance = 0.0;
    m_nCell_Input_Direction = 0;
    m_nCell_Output_Direction = 0;
	m_dYR_SubMark_Pos_X = 0;
	m_dYR_SubMark_Pos_Y = 0;
	m_dYR_SubMark_Distance = 0;

    m_dCellThickness = 0.0;
    m_dPolThickness = 0.0;
	m_dYSideSelect = 0.0;
    /**Tab 관련 Data [48개]*/
    m_dXu_Tab_Qty = 0.0;
    m_dXd_Tab_Qty = 0.0;
    m_dY_Tab_Qty = 0.0;
    /** Tab 관련 Data [22개] */
    m_dR_Lead_Pitch_X = 0.0;
    m_dR_Lead_Pitch_Y = 0.0;
    m_dC_Lead_Pitch_X = 0.0;
    m_dC_Lead_Pitch_Y = 0.0;
    m_dLead_Width_Value_X = 0.0;
    m_dLead_Width_Value_Y = 0.0;
    m_dTape_Pitch_Value_X = 0.0;
    m_dTape_Pitch_Value_Y = 0.0;
    m_dSprocket_Value_X = 0.0;
    m_dSprocket_Value_Y = 0.0;
    m_nTab_Direction_X = 0;
    m_nTab_Direction_Y = 0;
    m_dTheta_Tolerance_X = 0.0;
    m_dTheta_Tolerance_Y = 0.0;
    m_dX_Tab_Center_X = 0.0;
    m_dX_Tab_Center_Y = 0.0;
    m_dY_Tab_Center_X = 0.0;
    m_dY_Tab_Center_Y = 0.0;
    m_nBad_Tab_Count_X = 0;
    m_nBad_Tab_Count_Y = 0;
    m_nVisionSceneNumber = 0;
	m_nUsingStageSelect = 0;
	m_iMaterialType	= 0; //SJ_YYK 111101 Add...
	m_dMarkToStageedgeLengthX = 0;
	m_dMarkToStageedgeLengthY = 0;
}

CCellData::~CCellData()
{
}

int CCellData::ReadCellData()
{
	TCHAR eMsg[200];
	TCHAR eMsg1[200];
	BOOL ret = TRUE;
	CString strItem;
	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));
	
	CMyProgressWnd ProgWnd(NULL, _T("Model Data File Loading..."));
	ProgWnd.SetRange(0,96);
	ProgWnd.SetText(_T("Cell Data Loading....\n")
		_T("<<Cell Data File을 Loading 중 입니다.\n")
					    _T("잠시만 기다려 주세요...>>"));
	ProgWnd.PeekAndPump();
	/** [Cell Data]*/
	if(!GetValue(_T("Cell Data"), _T("CellSize_X"), &m_dCellSize_X))
	{
		swprintf(eMsg, _T("[Cell Data] CellSize_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("CellSize_Y"), &m_dCellSize_Y))
	{
		swprintf(eMsg, _T("[Cell Data] CellSize_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Use_Xu"), &m_flgUse_Xu))
	{
		swprintf(eMsg, _T("[Cell Data] Use_Xu 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_X"), &m_dXu_CellMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_CellMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_Y"), &m_dXu_CellMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_CellMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Distance"), &m_dXu_CellMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_CellMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

/* 
	if(!GetValue(_T("Cell Data"), _T("UsingStageSelect"), &m_nUsingStageSelect))
	{
		swprintf(eMsg, _T("[Cell Data] UsingStageSelect 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
*/
	if(!GetValue(_T("Cell Data"), _T("Use_Xd"), &m_flgUse_Xd))
	{
		swprintf(eMsg, _T("[Cell Data] Use_Xd 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_X"), &m_dXd_CellMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_CellMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_Y"), &m_dXd_CellMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_CellMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Distance"), &m_dXd_CellMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_CellMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Use_Y"), &m_flgUse_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Use_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Pos_X"), &m_dY_CellMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Y_CellMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Pos_Y"), &m_dY_CellMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Y_CellMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Distance"), &m_dY_CellMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Y_CellMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Cell_Input_Direction"), &m_nCell_Input_Direction))
	{
		swprintf(eMsg, _T("[Cell Data] Cell_Input_Direction 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Cell_Output_Direction"), &m_nCell_Output_Direction))
	{
		swprintf(eMsg, _T("[Cell Data] Cell_Output_Direction 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_X"), &m_dXu_SubMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_SubMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_Y"), &m_dXu_SubMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_SubMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Distance"), &m_dXu_SubMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Xu_SubMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_X"), &m_dXd_SubMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_SubMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_Y"), &m_dXd_SubMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_SubMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Distance"), &m_dXd_SubMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Xd_SubMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Pos_X"), &m_dY_SubMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] Y_SubMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Pos_Y"), &m_dY_SubMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] Y_SubMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Distance"), &m_dY_SubMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] Y_SubMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();



	if(!GetValue(_T("Cell Data"), _T("Use_YR"), &m_flgUse_YR))
	{
		swprintf(eMsg, _T("[Cell Data] Use_YR 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Pos_X"), &m_dYR_CellMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] YR_CellMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Pos_Y"), &m_dYR_CellMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] YR_CellMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Distance"), &m_dYR_CellMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] YR_CellMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Pos_X"), &m_dYR_SubMark_Pos_X))
	{
		swprintf(eMsg, _T("[Cell Data] YR_SubMark_Pos_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Pos_Y"), &m_dYR_SubMark_Pos_Y))
	{
		swprintf(eMsg, _T("[Cell Data] YR_SubMark_Pos_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Distance"), &m_dYR_SubMark_Distance))
	{
		swprintf(eMsg, _T("[Cell Data] YR_SubMark_Distance 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();


	if(!GetValue(_T("Cell Data"), _T("Cell Thickness"), &m_dCellThickness))
	{
		swprintf(eMsg, _T("[Cell Data]Cell Thickness 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Pol Thickness"), &m_dPolThickness))
	{
		swprintf(eMsg, _T("[Cell Data] Pol Thickness 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	m_iMaterialType = 0; //SJ_YYK 111101 Add...
	if(!GetValue(_T("Cell Data"), _T("MaterialSelect"), &m_nMaterialSelect))
	{
		swprintf(eMsg, _T("[Cell Data] MaterialSelect 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();


	/** [Tab Data]*/
	if(!GetValue(_T("Tab Data"), _T("Xu_Tab_Qty"), &m_dXu_Tab_Qty))
	{
		swprintf(eMsg, _T("[Tab Data] Xu_Tab_Qty 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(int i=0; i<20; i++)
	{
		strItem.Format(_T("Xu_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dXu_Tab_Pitch[i]))
		{
			swprintf(eMsg, _T("[Tab Data] Xu_Tab_Pitch_%d 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"), i+1);
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("Xd_Tab_Qty"), &m_dXd_Tab_Qty))
	{
		swprintf(eMsg, _T("[Tab Data] Xd_Tab_Qty 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	if(!GetValue(_T("Cell Data"), _T("YSideSelect"), &m_dYSideSelect))
	{
		swprintf(eMsg, _T("[Cell Data] YSideSelect 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(i=0; i<20; i++)
	{
		strItem.Format(_T("Xd_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dXd_Tab_Pitch[i]))
		{
			swprintf(eMsg, _T("[Tab Data] Xd_Tab_Pitch_%d 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"), i+1);
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Qty"), &m_dY_Tab_Qty))
	{
		swprintf(eMsg, _T("[Tab Data] Y_Tab_Qty 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(i=0; i<15; i++)
	{
		strItem.Format(_T("Y_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dY_Tab_Pitch[i]))
		{
			swprintf(eMsg, _T("[Tab Data] Y_Tab_Pitch_%d 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"), i+1);
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("R_Lead_Pitch_X"), &m_dR_Lead_Pitch_X))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("R_Lead_Pitch_Y"), &m_dR_Lead_Pitch_Y))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("C_Lead_Pitch_X"), &m_dC_Lead_Pitch_X))
	{
		swprintf(eMsg, _T("[Tab Data] C_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("C_Lead_Pitch_Y"), &m_dC_Lead_Pitch_Y))
	{
		swprintf(eMsg, _T("[Tab Data] C_Lead_Pitch_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Lead_Width_Value_X"), &m_dLead_Width_Value_X))
	{
		swprintf(eMsg, _T("[Tab Data] Lead_Width_Value_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Lead_Width_Value_Y"), &m_dLead_Width_Value_Y))
	{
		swprintf(eMsg, _T("[Tab Data] Lead_Width_Value_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tape_Pitch_Value_X"), &m_dTape_Pitch_Value_X))
	{
		swprintf(eMsg, _T("[Tab Data] Tape_Pitch_Value_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tape_Pitch_Value_Y"), &m_dTape_Pitch_Value_Y))
	{
		swprintf(eMsg, _T("[Tab Data] Tape_Pitch_Value_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Sprocket_Value_X"), &m_dSprocket_Value_X))
	{
		swprintf(eMsg, _T("[Tab Data] Sprocket_Value_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Sprocket_Value_Y"), &m_dSprocket_Value_Y))
	{
		swprintf(eMsg, _T("[Tab Data] Sprocket_Value_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tab_Direction_X"), &m_nTab_Direction_X))
	{
		swprintf(eMsg, _T("[Tab Data] Tab_Direction_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tab_Direction_Y"), &m_nTab_Direction_Y))
	{
		swprintf(eMsg, _T("[Tab Data] Tab_Direction_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Theta_Tolerance_X"), &m_dTheta_Tolerance_X))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Theta_Tolerance_Y"), &m_dTheta_Tolerance_Y))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("X_Tab_Center_X"), &m_dX_Tab_Center_X))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("X_Tab_Center_Y"), &m_dX_Tab_Center_Y))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Center_X"), &m_dY_Tab_Center_X))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Center_Y"), &m_dY_Tab_Center_Y))
	{
		swprintf(eMsg, _T("[Tab Data] R_Lead_Pitch_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Bad_Tab_Count_X"), &m_nBad_Tab_Count_X))
	{
		swprintf(eMsg, _T("[Tab Data] Bad_Tab_Count_X 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Bad_Tab_Count_Y"), &m_nBad_Tab_Count_Y))
	{
		swprintf(eMsg, _T("[Tab Data] Bad_Tab_Count_Y 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("VisionSceneNumber"), &m_nVisionSceneNumber))
	{
		swprintf(eMsg, _T("[Tab Data] VisionSceneNumber 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthX"), &m_dMarkToStageedgeLengthX))
	{
		swprintf(eMsg, _T("[Tab Data] dMarkToStageedgeLengthX 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthY"), &m_dMarkToStageedgeLengthY))
	{
		swprintf(eMsg, _T("[Tab Data] dMarkToStageedgeLengthY 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	//SJ_YYK 111101 Add..
	if(!GetValue(_T("Cell Data"), _T("iMaterialType"), &m_iMaterialType))
	{
		swprintf(eMsg, _T("[Tab Data] iMaterialType 항목을 읽지 못했습니다. 다음 항목을 계속 읽겠습니까?"));
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	//_______________________*/
	return ret;
	return ret;
}

int CCellData::WriteCellData()
{
	TCHAR eMsg[200];
	TCHAR eMsg1[200];
	BOOL ret = TRUE;
	CString strItem;
	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));

	if(!MakeBackUpFile())
	{
		if(MyMessageBox(_T("Failed to make a back up file. Do you proceed it?\r\n") 
			_T("<< Back up file을 만드는데 실패했습니다. 계속 진행하겠습니까?>>"), _T("File Write Error"), M_ICONERROR|M_YESNO) == IDNO) 
			return FALSE;
	}
	
	CMyProgressWnd ProgWnd(NULL, _T("Model Data File Saving..."));
	ProgWnd.SetRange(0,95);
	ProgWnd.SetText(_T("Cell Data saving....\n")
		_T("<<Cell Data File을 저장 중 입니다.\n")
					    _T("잠시만 기다려 주세요...>>"));
	ProgWnd.PeekAndPump();

	/** [Cell Data]*/
	if(!SetValue(_T("Cell Data"), _T("CellSize_X"), m_dCellSize_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("CellSize_Y"), m_dCellSize_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Xu"), m_flgUse_Xu)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_X"), m_dXu_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_Y"), m_dXu_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Distance"), m_dXu_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Xd"), m_flgUse_Xd)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_X"), m_dXd_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_Y"), m_dXd_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Distance"), m_dXd_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Y"), m_flgUse_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Pos_X"), m_dY_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Pos_Y"), m_dY_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Distance"), m_dY_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Cell_Input_Direction"), m_nCell_Input_Direction)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Cell_Output_Direction"), m_nCell_Output_Direction)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_X"), m_dXu_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_Y"), m_dXu_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Distance"), m_dXu_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_X"), m_dXd_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_Y"), m_dXd_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Distance"), m_dXd_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Pos_X"), m_dY_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Pos_Y"), m_dY_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Distance"), m_dY_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();


	if(!SetValue(_T("Cell Data"), _T("Use_YR"), m_flgUse_YR)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Pos_X"), m_dYR_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Pos_Y"), m_dYR_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Distance"), m_dYR_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Pos_X"), m_dYR_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Pos_Y"), m_dYR_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Distance"), m_dYR_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();

	if(!SetValue(_T("Cell Data"), _T("Cell Thickness"), m_dCellThickness)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Pol Thickness"), m_dPolThickness)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YSideSelect"), m_dYSideSelect)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("MaterialSelect"), m_nMaterialSelect)) ret = FALSE;
	ProgWnd.StepIt();

	/** [Tab Data]*/
	if(!SetValue(_T("Tab Data"), _T("Xu_Tab_Qty"), m_dXu_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(int i=0; i<20; i++)
	{
		strItem.Format(_T("Xu_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dXu_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}

	if(!SetValue(_T("Tab Data"), _T("Xd_Tab_Qty"), m_dXd_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(i=0; i<20; i++)
	{
		strItem.Format(_T("Xd_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dXd_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}

	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Qty"), m_dY_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(i=0; i<15; i++)
	{
		strItem.Format(_T("Y_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dY_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}
	if(!SetValue(_T("Tab Data"), _T("R_Lead_Pitch_X"), m_dR_Lead_Pitch_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("R_Lead_Pitch_Y"), m_dR_Lead_Pitch_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("C_Lead_Pitch_X"), m_dC_Lead_Pitch_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("C_Lead_Pitch_Y"), m_dC_Lead_Pitch_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Lead_Width_Value_X"), m_dLead_Width_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Lead_Width_Value_Y"), m_dLead_Width_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tape_Pitch_Value_X"), m_dTape_Pitch_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tape_Pitch_Value_Y"), m_dTape_Pitch_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Sprocket_Value_X"), m_dSprocket_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Sprocket_Value_Y"), m_dSprocket_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tab_Direction_X"), m_nTab_Direction_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tab_Direction_Y"), m_nTab_Direction_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Theta_Tolerance_X"), m_dTheta_Tolerance_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Theta_Tolerance_Y"), m_dTheta_Tolerance_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("X_Tab_Center_X"), m_dX_Tab_Center_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("X_Tab_Center_Y"), m_dX_Tab_Center_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Center_X"), m_dY_Tab_Center_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Center_Y"), m_dY_Tab_Center_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Bad_Tab_Count_X"), m_nBad_Tab_Count_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Bad_Tab_Count_Y"), m_nBad_Tab_Count_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("VisionSceneNumber"), m_nVisionSceneNumber)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("UsingStageSelect"), m_nUsingStageSelect)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthX"), m_dMarkToStageedgeLengthX)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthY"), m_dMarkToStageedgeLengthY)) ret = FALSE;
	ProgWnd.StepIt();
	//SJ_YYK 111101 Add..
	if(!SetValue(_T("Cell Data"), _T("iMaterialType"), m_iMaterialType)) ret = FALSE;
	ProgWnd.StepIt();
	//________________________*/


	if(!ret)
	{
		swprintf(eMsg, _T("%s File is an incorrect."), m_strFileName);
		swprintf(eMsg1, _T("%s File Write Error!"), m_strFileName);
		MyMessageBox(eMsg, eMsg1, M_ICONERROR);
		return FALSE;
	}

	return TRUE;
}

void CCellData::SetMaterialSelect(UINT nMaterialSelect)
{
	assert(nMaterialSelect == SOURCE_SIDE || nMaterialSelect == GATE_SIDE || nMaterialSelect == SOURCE_N_GATE_SIDE); 
	m_nMaterialSelect = nMaterialSelect;
}
/** Model Data가 있는 Path를 설정 하는 함수 */
void CCellData::SetModelPath(CString strPath)
{
	SetFilePath(strPath);
}
