/* Generated by Together */

#include "Stdafx.h"
#include "CCellData.h"
#include "../Util/Common.h" //191227 JSH
#include "../Util/MinUtilExt.h"
#include "../Util/MyProgressWnd.h"

CCellData::CCellData(CString strFileName, CString strPath) : CFileManager(strFileName, strPath)
{
	memset(m_dXu_Tab_Pitch, 0, sizeof(m_dXu_Tab_Pitch));
    memset(m_dXd_Tab_Pitch, 0, sizeof(m_dXd_Tab_Pitch));
    memset(m_dY_Tab_Pitch, 0, sizeof(m_dY_Tab_Pitch));

	/** Model Data */
    m_dCellSize_X = 0.0;
    m_dCellSize_Y = 0.0;
    m_flgUse_Xu = 0;
    m_dXu_CellMark_Pos_X = 0.0;
    m_dXu_CellMark_Pos_Y = 0.0;
    m_dXu_CellMark_Distance = 0.0;
    m_flgUse_Xd = 0;
    m_dXd_CellMark_Pos_X = 0.0;
    m_dXd_CellMark_Pos_Y = 0.0;
    m_dXd_CellMark_Distance = 0.0;
    m_flgUse_Y = 0;
    m_dY_CellMark_Pos_X = 0.0;
    m_dY_CellMark_Pos_Y = 0.0;
    m_dY_CellMark_Distance = 0.0;
    m_flgUse_YR = 0;
    m_dYR_CellMark_Pos_X = 0.0;
    m_dYR_CellMark_Pos_Y = 0.0;
    m_dYR_CellMark_Distance = 0.0;
    m_nCell_Input_Direction = 0;
    m_nCell_Output_Direction = 0;
    /**Tab 관련 Data [48개]*/
    m_dXu_Tab_Qty = 0.0;
    m_dXd_Tab_Qty = 0.0;
    m_dY_Tab_Qty = 0.0;
    /** Tab 관련 Data [22개] */
    m_dR_Lead_Pitch_X = 0.0;
    m_dR_Lead_Pitch_Y = 0.0;
    m_dC_Lead_Pitch_X = 0.0;
    m_dC_Lead_Pitch_Y = 0.0;
    m_dLead_Width_Value_X = 0.0;
    m_dLead_Width_Value_Y = 0.0;
    m_dTape_Pitch_Value_X = 0.0;
    m_dTape_Pitch_Value_Y = 0.0;
    m_dSprocket_Value_X = 0.0;
    m_dSprocket_Value_Y = 0.0;
    m_nTab_Direction_X = 0;
    m_nTab_Direction_Y = 0;
    m_dTheta_Tolerance_X = 0.0;
    m_dTheta_Tolerance_Y = 0.0;
    m_dX_Tab_Center_X = 0.0;
    m_dX_Tab_Center_Y = 0.0;
    m_dY_Tab_Center_X = 0.0;
    m_dY_Tab_Center_Y = 0.0;
    m_nBad_Tab_Count_X = 0;
    m_nBad_Tab_Count_Y = 0;
    m_nVisionSceneNumber = 0;
    m_dCellThickness = 0.0;
    m_dPolThickness = 0.0;
	m_dYSideSelect = 0.0;
	m_nUsingStageSelect = 0;
	m_dMarkToStageedgeLengthX = 0;
	m_dMarkToStageedgeLengthY = 0;
}

CCellData::CCellData(CString strFileName) : CFileManager(strFileName)
{
	memset(m_dXu_Tab_Pitch, 0, sizeof(m_dXu_Tab_Pitch));
    memset(m_dXd_Tab_Pitch, 0, sizeof(m_dXd_Tab_Pitch));
    memset(m_dY_Tab_Pitch, 0, sizeof(m_dY_Tab_Pitch));

	/** Model Data */
    m_dCellSize_X = 0.0;
    m_dCellSize_Y = 0.0;
    m_flgUse_Xu = 0;
    m_dXu_CellMark_Pos_X = 0.0;
    m_dXu_CellMark_Pos_Y = 0.0;
    m_dXu_CellMark_Distance = 0.0;
    m_flgUse_Xd = 0;
    m_dXd_CellMark_Pos_X = 0.0;
    m_dXd_CellMark_Pos_Y = 0.0;
    m_dXd_CellMark_Distance = 0.0;
    m_flgUse_Y = 0;
    m_dY_CellMark_Pos_X = 0.0;
    m_dY_CellMark_Pos_Y = 0.0;
    m_dY_CellMark_Distance = 0.0;
    m_flgUse_YR = 0;
    m_dYR_CellMark_Pos_X = 0.0;
    m_dYR_CellMark_Pos_Y = 0.0;
    m_dYR_CellMark_Distance = 0.0;
    m_nCell_Input_Direction = 0;
    m_nCell_Output_Direction = 0;
	m_dYR_SubMark_Pos_X = 0;
	m_dYR_SubMark_Pos_Y = 0;
	m_dYR_SubMark_Distance = 0;

    m_dCellThickness = 0.0;
    m_dPolThickness = 0.0;
	m_dYSideSelect = 0.0;
    /**Tab 관련 Data [48개]*/
    m_dXu_Tab_Qty = 0.0;
    m_dXd_Tab_Qty = 0.0;
    m_dY_Tab_Qty = 0.0;
    /** Tab 관련 Data [22개] */
    m_dR_Lead_Pitch_X = 0.0;
    m_dR_Lead_Pitch_Y = 0.0;
    m_dC_Lead_Pitch_X = 0.0;
    m_dC_Lead_Pitch_Y = 0.0;
    m_dLead_Width_Value_X = 0.0;
    m_dLead_Width_Value_Y = 0.0;
    m_dTape_Pitch_Value_X = 0.0;
    m_dTape_Pitch_Value_Y = 0.0;
    m_dSprocket_Value_X = 0.0;
    m_dSprocket_Value_Y = 0.0;
    m_nTab_Direction_X = 0;
    m_nTab_Direction_Y = 0;
    m_dTheta_Tolerance_X = 0.0;
    m_dTheta_Tolerance_Y = 0.0;
    m_dX_Tab_Center_X = 0.0;
    m_dX_Tab_Center_Y = 0.0;
    m_dY_Tab_Center_X = 0.0;
    m_dY_Tab_Center_Y = 0.0;
    m_nBad_Tab_Count_X = 0;
    m_nBad_Tab_Count_Y = 0;
    m_nVisionSceneNumber = 0;
	m_nUsingStageSelect = 0;
	m_iMaterialType	= 0; //SJ_YYK 111101 Add...
	m_dMarkToStageedgeLengthX = 0;
	m_dMarkToStageedgeLengthY = 0;
}

CCellData::~CCellData()
{
}

int CCellData::ReadCellData()
{
	TCHAR eMsg[200];
	TCHAR eMsg1[200];
	BOOL ret = TRUE;
	CString strItem;
	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));
	
	CMyProgressWnd ProgWnd(NULL, _T("Model Data File Loading..."));
	ProgWnd.SetRange(0,96);
	ProgWnd.SetText(_T("Cell Data Loading....\n")
		ReadDisplayMessage(_T("CCellData.cpp_001"))//200212 auto.JSH
					    ReadDisplayMessage(_T("CCellData.cpp_002")));//200212 auto.JSH
	ProgWnd.PeekAndPump();
	/** [Cell Data]*/
	if(!GetValue(_T("Cell Data"), _T("CellSize_X"), &m_dCellSize_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_003")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("CellSize_Y"), &m_dCellSize_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_004")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Use_Xu"), &m_flgUse_Xu))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_005")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_X"), &m_dXu_CellMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_006")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_Y"), &m_dXu_CellMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_007")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_CellMark_Distance"), &m_dXu_CellMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_008")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

/* 
	if(!GetValue(_T("Cell Data"), _T("UsingStageSelect"), &m_nUsingStageSelect))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_009")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
*/
	if(!GetValue(_T("Cell Data"), _T("Use_Xd"), &m_flgUse_Xd))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_010")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_X"), &m_dXd_CellMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_011")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_Y"), &m_dXd_CellMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_012")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_CellMark_Distance"), &m_dXd_CellMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_013")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Use_Y"), &m_flgUse_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_014")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Pos_X"), &m_dY_CellMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_015")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Pos_Y"), &m_dY_CellMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_016")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_CellMark_Distance"), &m_dY_CellMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_017")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Cell_Input_Direction"), &m_nCell_Input_Direction))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_018")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Cell_Output_Direction"), &m_nCell_Output_Direction))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_019")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_X"), &m_dXu_SubMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_020")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_Y"), &m_dXu_SubMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_021")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xu_SubMark_Distance"), &m_dXu_SubMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_022")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_X"), &m_dXd_SubMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_023")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_Y"), &m_dXd_SubMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_024")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Xd_SubMark_Distance"), &m_dXd_SubMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_025")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Pos_X"), &m_dY_SubMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_026")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Pos_Y"), &m_dY_SubMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_027")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Y_SubMark_Distance"), &m_dY_SubMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_028")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();



	if(!GetValue(_T("Cell Data"), _T("Use_YR"), &m_flgUse_YR))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_029")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Pos_X"), &m_dYR_CellMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_030")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Pos_Y"), &m_dYR_CellMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_031")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_CellMark_Distance"), &m_dYR_CellMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_032")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Pos_X"), &m_dYR_SubMark_Pos_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_033")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Pos_Y"), &m_dYR_SubMark_Pos_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_034")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("YR_SubMark_Distance"), &m_dYR_SubMark_Distance))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_035")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();


	if(!GetValue(_T("Cell Data"), _T("Cell Thickness"), &m_dCellThickness))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_036")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("Pol Thickness"), &m_dPolThickness))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_037")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	m_iMaterialType = 0; //SJ_YYK 111101 Add...
	if(!GetValue(_T("Cell Data"), _T("MaterialSelect"), &m_nMaterialSelect))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_038")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();


	/** [Tab Data]*/
	if(!GetValue(_T("Tab Data"), _T("Xu_Tab_Qty"), &m_dXu_Tab_Qty))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_039")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(int i=0; i<20; i++)
	{
		strItem.Format(_T("Xu_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dXu_Tab_Pitch[i]))
		{
			swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_040")), i+1);//200212 auto.JSH
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("Xd_Tab_Qty"), &m_dXd_Tab_Qty))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_041")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	if(!GetValue(_T("Cell Data"), _T("YSideSelect"), &m_dYSideSelect))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_042")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(i=0; i<20; i++)
	{
		strItem.Format(_T("Xd_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dXd_Tab_Pitch[i]))
		{
			swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_043")), i+1);//200212 auto.JSH
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Qty"), &m_dY_Tab_Qty))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_044")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();

	for(i=0; i<15; i++)
	{
		strItem.Format(_T("Y_Tab_Pitch_%d"), i+1);
		if(!GetValue(_T("Tab Data"), strItem, &m_dY_Tab_Pitch[i]))
		{
			swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_045")), i+1);//200212 auto.JSH
			swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
			if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
			ret = FALSE;
		}
		ProgWnd.StepIt();
	}

	if(!GetValue(_T("Tab Data"), _T("R_Lead_Pitch_X"), &m_dR_Lead_Pitch_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_046")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("R_Lead_Pitch_Y"), &m_dR_Lead_Pitch_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_047")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("C_Lead_Pitch_X"), &m_dC_Lead_Pitch_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_048")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("C_Lead_Pitch_Y"), &m_dC_Lead_Pitch_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_049")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Lead_Width_Value_X"), &m_dLead_Width_Value_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_050")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Lead_Width_Value_Y"), &m_dLead_Width_Value_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_051")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tape_Pitch_Value_X"), &m_dTape_Pitch_Value_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_052")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tape_Pitch_Value_Y"), &m_dTape_Pitch_Value_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_053")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Sprocket_Value_X"), &m_dSprocket_Value_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_054")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Sprocket_Value_Y"), &m_dSprocket_Value_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_055")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tab_Direction_X"), &m_nTab_Direction_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_056")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Tab_Direction_Y"), &m_nTab_Direction_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_057")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Theta_Tolerance_X"), &m_dTheta_Tolerance_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_058")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Theta_Tolerance_Y"), &m_dTheta_Tolerance_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_059")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("X_Tab_Center_X"), &m_dX_Tab_Center_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_060")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("X_Tab_Center_Y"), &m_dX_Tab_Center_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_061")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Center_X"), &m_dY_Tab_Center_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_062")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Y_Tab_Center_Y"), &m_dY_Tab_Center_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_063")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Bad_Tab_Count_X"), &m_nBad_Tab_Count_X))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_064")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("Bad_Tab_Count_Y"), &m_nBad_Tab_Count_Y))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_065")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Tab Data"), _T("VisionSceneNumber"), &m_nVisionSceneNumber))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_066")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthX"), &m_dMarkToStageedgeLengthX))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_067")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	if(!GetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthY"), &m_dMarkToStageedgeLengthY))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_068")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	//SJ_YYK 111101 Add..
	if(!GetValue(_T("Cell Data"), _T("iMaterialType"), &m_iMaterialType))
	{
		swprintf(eMsg, ReadDisplayMessage(_T("CCellData.cpp_069")));//200212 auto.JSH
		swprintf(eMsg1, _T("%s File Read Error!"), m_strFileName);
		if(MyMessageBox(eMsg, eMsg1, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}
	ProgWnd.StepIt();
	//_______________________*/
	return ret;
	return ret;
}

int CCellData::WriteCellData()
{
	TCHAR eMsg[200];
	TCHAR eMsg1[200];
	BOOL ret = TRUE;
	CString strItem;
	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));

	if(!MakeBackUpFile())
	{
		if(MyMessageBox(_T("Failed to make a back up file. Do you proceed it?\r\n") 
			ReadDisplayMessage(_T("CCellData.cpp_070")), _T("File Write Error"), M_ICONERROR|M_YESNO) == IDNO) //200212 auto.JSH
			return FALSE;
	}
	
	CMyProgressWnd ProgWnd(NULL, _T("Model Data File Saving..."));
	ProgWnd.SetRange(0,95);
	ProgWnd.SetText(_T("Cell Data saving....\n")
		ReadDisplayMessage(_T("CCellData.cpp_071"))//200212 auto.JSH
					    ReadDisplayMessage(_T("CCellData.cpp_072")));//200212 auto.JSH
	ProgWnd.PeekAndPump();

	/** [Cell Data]*/
	if(!SetValue(_T("Cell Data"), _T("CellSize_X"), m_dCellSize_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("CellSize_Y"), m_dCellSize_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Xu"), m_flgUse_Xu)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_X"), m_dXu_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Pos_Y"), m_dXu_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_CellMark_Distance"), m_dXu_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Xd"), m_flgUse_Xd)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_X"), m_dXd_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Pos_Y"), m_dXd_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_CellMark_Distance"), m_dXd_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Use_Y"), m_flgUse_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Pos_X"), m_dY_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Pos_Y"), m_dY_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_CellMark_Distance"), m_dY_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Cell_Input_Direction"), m_nCell_Input_Direction)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Cell_Output_Direction"), m_nCell_Output_Direction)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_X"), m_dXu_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Pos_Y"), m_dXu_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xu_SubMark_Distance"), m_dXu_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_X"), m_dXd_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Pos_Y"), m_dXd_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Xd_SubMark_Distance"), m_dXd_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Pos_X"), m_dY_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Pos_Y"), m_dY_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Y_SubMark_Distance"), m_dY_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();


	if(!SetValue(_T("Cell Data"), _T("Use_YR"), m_flgUse_YR)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Pos_X"), m_dYR_CellMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Pos_Y"), m_dYR_CellMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_CellMark_Distance"), m_dYR_CellMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Pos_X"), m_dYR_SubMark_Pos_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Pos_Y"), m_dYR_SubMark_Pos_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YR_SubMark_Distance"), m_dYR_SubMark_Distance)) ret = FALSE;
	ProgWnd.StepIt();

	if(!SetValue(_T("Cell Data"), _T("Cell Thickness"), m_dCellThickness)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("Pol Thickness"), m_dPolThickness)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("YSideSelect"), m_dYSideSelect)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("MaterialSelect"), m_nMaterialSelect)) ret = FALSE;
	ProgWnd.StepIt();

	/** [Tab Data]*/
	if(!SetValue(_T("Tab Data"), _T("Xu_Tab_Qty"), m_dXu_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(int i=0; i<20; i++)
	{
		strItem.Format(_T("Xu_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dXu_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}

	if(!SetValue(_T("Tab Data"), _T("Xd_Tab_Qty"), m_dXd_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(i=0; i<20; i++)
	{
		strItem.Format(_T("Xd_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dXd_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}

	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Qty"), m_dY_Tab_Qty)) ret = FALSE;
	ProgWnd.StepIt();
	for(i=0; i<15; i++)
	{
		strItem.Format(_T("Y_Tab_Pitch_%d"), i+1);
		if(!SetValue(_T("Tab Data"), strItem, m_dY_Tab_Pitch[i])) ret = FALSE;
		ProgWnd.StepIt();
	}
	if(!SetValue(_T("Tab Data"), _T("R_Lead_Pitch_X"), m_dR_Lead_Pitch_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("R_Lead_Pitch_Y"), m_dR_Lead_Pitch_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("C_Lead_Pitch_X"), m_dC_Lead_Pitch_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("C_Lead_Pitch_Y"), m_dC_Lead_Pitch_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Lead_Width_Value_X"), m_dLead_Width_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Lead_Width_Value_Y"), m_dLead_Width_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tape_Pitch_Value_X"), m_dTape_Pitch_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tape_Pitch_Value_Y"), m_dTape_Pitch_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Sprocket_Value_X"), m_dSprocket_Value_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Sprocket_Value_Y"), m_dSprocket_Value_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tab_Direction_X"), m_nTab_Direction_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Tab_Direction_Y"), m_nTab_Direction_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Theta_Tolerance_X"), m_dTheta_Tolerance_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Theta_Tolerance_Y"), m_dTheta_Tolerance_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("X_Tab_Center_X"), m_dX_Tab_Center_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("X_Tab_Center_Y"), m_dX_Tab_Center_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Center_X"), m_dY_Tab_Center_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Y_Tab_Center_Y"), m_dY_Tab_Center_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Bad_Tab_Count_X"), m_nBad_Tab_Count_X)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("Bad_Tab_Count_Y"), m_nBad_Tab_Count_Y)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Tab Data"), _T("VisionSceneNumber"), m_nVisionSceneNumber)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("UsingStageSelect"), m_nUsingStageSelect)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthX"), m_dMarkToStageedgeLengthX)) ret = FALSE;
	ProgWnd.StepIt();
	if(!SetValue(_T("Cell Data"), _T("dMarkToStageedgeLengthY"), m_dMarkToStageedgeLengthY)) ret = FALSE;
	ProgWnd.StepIt();
	//SJ_YYK 111101 Add..
	if(!SetValue(_T("Cell Data"), _T("iMaterialType"), m_iMaterialType)) ret = FALSE;
	ProgWnd.StepIt();
	//________________________*/


	if(!ret)
	{
		swprintf(eMsg, _T("%s File is an incorrect."), m_strFileName);
		swprintf(eMsg1, _T("%s File Write Error!"), m_strFileName);
		MyMessageBox(eMsg, eMsg1, M_ICONERROR);
		return FALSE;
	}

	return TRUE;
}

void CCellData::SetMaterialSelect(UINT nMaterialSelect)
{
	assert(nMaterialSelect == SOURCE_SIDE || nMaterialSelect == GATE_SIDE || nMaterialSelect == SOURCE_N_GATE_SIDE); 
	m_nMaterialSelect = nMaterialSelect;
}
/** Model Data가 있는 Path를 설정 하는 함수 */
void CCellData::SetModelPath(CString strPath)
{
	SetFilePath(strPath);
}
